apiVersion: v1
kind: ServiceAccount
metadata:
  name: defrost-proxy-svc-acc
  namespace: default
automountServiceAccountToken: true
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: defrost-proxy-clusterrole-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: defrost-proxy-svc-acc
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
      targetPort: http
  selector:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: nginx
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx
    spec:
      containers:
        - name: nginx
          image: reg.captainjustin.space/nginx:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /
          livenessProbe:
            httpGet:
              port: http
              path: /
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
      name: http
      targetPort: http
  selector:
    app.kubernetes.io/instance: defrost-proxy
    app.kubernetes.io/name: defrost-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: defrost-proxy
  labels:
    app.kubernetes.io/name: defrost-proxy
    app.kubernetes.io/instance: defrost-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: defrost-proxy
      app.kubernetes.io/instance: defrost-proxy
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: defrost-proxy
        app.kubernetes.io/instance: defrost-proxy
    spec:
      serviceAccountName: defrost-proxy-svc-acc
      containers:
        - name: defrost-proxy
          image: reg.captainjustin.space/defrost-proxy:dev3
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:8080"
            - name: "REMOTE_ADDR"
              value: "nginx:8080"
            - name: "TARGET_NAMESPACE"
              value: "default"
            - name: "TARGET_NAME"
              value: "nginx"
