apiVersion: v1
kind: Namespace
metadata:
  name: coldfaas
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coldfaas-svc-acc
  namespace: "coldfaas"
automountServiceAccountToken: true
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coldfaas-clusterrole-binding
  namespace: "coldfaas"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: coldfaas-svc-acc
    namespace: "coldfaas"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-backend
  namespace: coldfaas
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
      targetPort: http
  selector:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: coldfaas
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: nginx
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx
    spec:
      serviceAccountName: coldfaas-svc-acc
      containers:
        - name: nginx
          image: reg.captainjustin.space/nginx:latest
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http
              path: /
          livenessProbe:
            httpGet:
              port: http
              path: /
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: coldfaas
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
      name: http
      targetPort: http
  selector:
    app.kubernetes.io/instance: coldfaas
    app.kubernetes.io/name: coldfaas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: coldfaas
  name: coldfaas
  labels:
    app.kubernetes.io/name: coldfaas
    app.kubernetes.io/instance: coldfaas
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: coldfaas
      app.kubernetes.io/instance: coldfaas
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coldfaas
        app.kubernetes.io/instance: coldfaas
    spec:
      serviceAccountName: coldfaas-svc-acc
      containers:
        - name: openfaas
          image: reg.captainjustin.space/coldfaas:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: "LOCAL_ADDR"
              value: "0.0.0.0:8080"
            - name: "REMOTE_ADDR"
              value: "nginx-backend:8080"
            - name: "TARGET_NAMESPACE"
              value: "coldfaas"
            - name: "TARGET_NAME"
              value: "nginx"
